#![allow(clippy::all)]
//! This lib contains abigen! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod erc20;
pub mod i_aave_oracle;
pub mod i_pool_addresses_provider;
pub mod i_pool_data_provider;
pub mod i_quoter_v2;
pub mod i_uniswap_v3_flash_callback;
pub mod i_uniswap_v3_pool_actions;
pub mod i_uniswap_v3_swap_callback;
pub mod il2_encoder;
pub mod il2_pool;
pub mod liquidator;
pub mod mock_oracle;
pub mod owned;
pub mod pool_address;
pub mod std_invariant;
pub mod std_style;
